workflows:
  unity-android:
    name: ZapNumber Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity
      unity: 6000.3.1f1
    scripts:
      - name: Build Android
        script: | 
          # 道具箱の場所を教えてからビルドを開始します
          $UNITY_HOME/Contents/MacOS/Unity \
            -batchmode \
            -projectPath . \
            -buildTarget Android \
            -executeMethod UnityEditor.BuildPlayerWindow.Build \
            -quit
    artifacts:
      - "*.apk"