workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      # ▼▼▼ あなたのPCと同じバージョンを指定します ▼▼▼
      unity: 6000.3.1f1
      groups:
        - unity
      vars:
        XCODE_PROJECT: "ios"
    scripts:
      - name: Build Xcode Project from Unity
        script: | 
          # これでCodemagicが正しいUnityを見つけられます
          echo "Unity Home is: $UNITY_HOME"
          
          # 念のためのチェック
          if [ -z "$UNITY_HOME" ]; then
            echo "Error: Unity path not found. Codemagic is installing it or failed to find it."
            exit 1
          fi

          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -

      - name: Build IPA from Xcode Project
        script: | 
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa