workflows:
  unity-android-ios:
    name: Unity Build (Android & iOS)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      unity: 6000.0.31f1 # Unity 6のバージョン指定
      vars:
        UNITY_BIN: /Applications/Unity/Hub/Editor/6000.0.31f1/Unity.app/Contents/MacOS/Unity
    scripts:
      - name: Build Android
        script: |
          # ここにAndroidビルドのコマンドが入ります
          echo "Building Android..."
      - name: Build iOS
        script: |
          # ここにiOSビルドのコマンドが入ります
          echo "Building iOS..."