workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity # ← これが「そっちの包丁を用意して」という合図です
      vars:
        XCODE_PROJECT: "ios"
    scripts:
      - name: Build Xcode Project from Unity
        script: | 
          # $UNITY_HOME は「CodemagicにあるUnityの場所」を指す魔法の言葉です
          echo "Using Unity at: $UNITY_HOME"
          
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -

      - name: Build IPA from Xcode Project
        script: | 
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa