workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity # Codemagic設定でこのグループを作っているか確認してください
      vars:
        UNITY_BIN: "/Applications/Unity/Unity.app/Contents/MacOS/Unity"
        XCODE_PROJECT: "ios"
    scripts:
      - name: Build Xcode Project from Unity
        script: |
          # Codemagicの標準的なパス、または手動指定のパスで実行を試みる
          $UNITY_BIN \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -

      - name: Build IPA from Xcode Project
        script: |
          # XcodeプロジェクトをIPAに変換
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa