workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      unity: 6000.3.1f1
      groups:
        - unity # 変数(USERNAME, PASSWORD)を読み込む
      vars:
        XCODE_PROJECT: "ios"
    scripts:
      - name: Activate Unity License
        script: |
          # パスワードを使ってログイン認証
          echo "Logging in to Unity..."
          
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode \
            -quit \
            -nographics \
            -username "$UNITY_USERNAME" \
            -password "$UNITY_PASSWORD" \
            -logFile -

      - name: Build Xcode Project from Unity
        script: | 
          echo "Building Xcode Project..."
          
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -

      - name: Build IPA from Xcode Project
        script: | 
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa