workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "ios"
    scripts:
      - name: Build Xcode Project from Unity
        script: | 
          $UNITY_HOME/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -
      - name: Build IPA from Xcode Project
        script: | 
          # 署名なし（または手動署名用）でIPAを作成
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa