workflows:
  unity-android:
    name: ZapNumber Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity
      unity: 6000.3.1f1
    scripts:
      - name: Build Android
        script: | 
          # 標準のビルドコマンドに変更しました
          $UNITY_HOME/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -projectPath . \
            -buildAndroidPlayer "ZapNumber.apk" \
            -quit
    artifacts:
      - "*.apk"