workflows:
  unity-ios:
    name: ZapNumber iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity # ←【重要】これでCodemagicがUnityの場所を準備してくれます
      vars:
        XCODE_PROJECT: "ios"
    scripts:
      - name: Build Xcode Project from Unity
        script: | 
          # $UNITY_HOME という「魔法の言葉」を使います
          # これなら場所がどこにあっても自動で読み替えてくれます
          $UNITY_HOME/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -executeMethod BuildScript.BuildIOS \
            -nographics \
            -projectPath . \
            -logFile -

      - name: Build IPA from Xcode Project
        script: | 
          xcode-project build-ipa \
            --workspace "$XCODE_PROJECT/Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/*.ipa