workflows:
  unity-android:
    name: ZapNumber Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity # 先ほど登録したメール・パス・シリアルのグループ名
      unity: 6000.3.1f1
    scripts:
      - name: Build Android
        script: | 
          # Unityを起動してビルドを実行する魔法のコマンド
          unity-cli build \
            --project . \
            --target Android \
            --output "build/android/ZapNumber.apk"
    artifacts:
      - build/android/*.apk